# Generated by Django 5.0.3 on 2024-03-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cl_id', models.AutoField(primary_key=True, serialize=False)),
                ('cl_name', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=50)),
                ('phone_num', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('num_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sailed_subs',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('cl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subscription')),
            ],
        ),
    ]
